
version: '3'
services:
  heimdall:
    image: linuxserver/heimdall:2.5.6
    container_name: heimdall
    volumes:
      - /home/user/appdata/heimdall:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 127.0.0.1:59999:80
      - 127.0.0.1:20934:443
    restart: unless-stopped
volumes:
  - database_volume:./heimdall_database/:/var/lib/mysql
  - gpg_volume:/etc/heimdall/gpg
  - jwt_volume:/etc/heimdall/jwt
